.\" Process this file with
.\" groff -man -Tascii ho22bus.1

.TH Ho22bus 1 "Oct 2010" User Manual
.SH NAME
ho22bus \- an education software to help people to study English, reciting english words. 
    It have very beautiful interface, make reciting word being a interesting things.
.SH OPTIONS
.IP -d
Show hodict Only. This is a dictionary with ho22bus.
.SH FILES
.IP ~/.ho22bus/my.cfg
User configure file.
.IP ~/.ho22bus/TTS or prefix/share/ho22bus/TTS
RealPeople Text to Sound files. Every word has a word.wav file, and storied in 26 directories.
.IP ~/.ho22bus/books or prefix/share/ho22bus/books
Words books.
.SH AUTHOR
YunQiang Su <wzssyqa@gmail.com>
